#!/bin/bash
# Quick reference for CI/CD Pipeline

echo "================================================"
echo "ForenSecure CI/CD Pipeline - Quick Reference"
echo "================================================"
echo ""
echo "🔄 Pipeline Stages (Sequential):"
echo "  1. Lint and Test (runs on all pushes to main)"
echo "  2. Build and Push (only if tests pass)"
echo "  3. Deploy (only if build succeeds)"
echo ""
echo "📊 Pipeline Components:"
echo ""
echo "LINT & TEST:"
echo "  ✓ Python 3.11 environment setup"
echo "  ✓ Dependency installation from requirements.txt"
echo "  ✓ Flake8 code quality checks"
echo "  ✓ Pytest test execution"
echo ""
echo "BUILD & PUSH:"
echo "  ✓ Docker BuildX setup for multi-platform builds"
echo "  ✓ GitHub Container Registry authentication"
echo "  ✓ Docker image build with caching"
echo "  ✓ Image push to ghcr.io"
echo ""
echo "DEPLOY:"
echo "  ✓ Ansible installation"
echo "  ✓ Docker pull from registry"
echo "  ✓ Container stop/remove (if exists)"
echo "  ✓ New container deployment"
echo "  ✓ Health verification"
echo ""
echo "🚀 To Trigger Pipeline:"
echo "  1. Make changes to files"
echo "  2. Commit: git commit -m 'your message'"
echo "  3. Push:   git push origin main"
echo "  4. View:   GitHub Actions tab in your repository"
echo ""
echo "🧪 Test Locally:"
echo "  pytest tests/ -v"
echo ""
echo "🔍 Lint Locally:"
echo "  flake8 cyber/ tests/"
echo ""
echo "🐳 Build Docker Locally:"
echo "  docker build -t forensecure:test ."
echo ""
echo "📋 Test Ansible Locally:"
echo "  ansible-playbook ansible/playbook.yml -i ansible/inventory.ini"
echo ""
echo "📖 For detailed setup: See .github/CICD_SETUP.md"
echo "================================================"
